import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">Welcome to tvDB</h1>

        <p className="description">The top 20 TV shows right now.</p>

        <div className="grid">
          <a href="https://nextjs.org/docs" className="card">
            <img src="https://picsum.photos/400" />
            <div>
              <h2>Documentation</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </div>
          </a>
        </div>
      </main>
    </div>
  );
}
