import Head from "next/head";
import Link from "next/link";

export default function Show() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <Link href="/">
          <a className="link">← Back to home</a>
        </Link>

        <h1 className="title">I am a dynamic page</h1>
      </main>
    </div>
  );
}
